import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'; // Import Link from Next.js

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'dQuiz',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icon: { apple: '/icon.png' },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          {/* Add a "Go Back" button linking to the home page */}
          <Link href="/">
            <button className='go-back-button'>Back to Home Page</button>
          </Link>
        </header>
        {children}
      </body>
    </html>
  )
}